"""Initial baseline

Revision ID: a1f82a6d225a
Revises: 
Create Date: 2026-01-05 09:02:43.860456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1f82a6d225a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('papers_fts_docsize')
    op.drop_table('papers_fts')
    op.drop_table('papers_fts_config')
    op.drop_table('papers_fts_data')
    op.drop_table('papers_fts_idx')
    op.create_index(op.f('ix_authors_name'), 'authors', ['name'], unique=False)
    op.create_index(op.f('ix_collections_name'), 'collections', ['name'], unique=False)
    op.create_index(op.f('ix_collections_parent_id'), 'collections', ['parent_id'], unique=False)
    op.create_index(op.f('ix_notes_note_type'), 'notes', ['note_type'], unique=False)
    op.create_index(op.f('ix_notes_paper_id'), 'notes', ['paper_id'], unique=False)
    op.create_index('ix_notes_paper_type', 'notes', ['paper_id', 'note_type'], unique=False)
    op.create_index(op.f('ix_paper_authors_author_id'), 'paper_authors', ['author_id'], unique=False)
    op.create_index('ix_paper_authors_both', 'paper_authors', ['paper_id', 'author_id'], unique=False)
    op.create_index(op.f('ix_paper_authors_paper_id'), 'paper_authors', ['paper_id'], unique=False)
    op.create_index(op.f('ix_paper_collections_collection_id'), 'paper_collections', ['collection_id'], unique=False)
    op.create_index(op.f('ix_paper_collections_paper_id'), 'paper_collections', ['paper_id'], unique=False)
    op.alter_column('paper_references', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_paper_refs_doi'), table_name='paper_references')
    op.drop_index(op.f('ix_paper_refs_match_status'), table_name='paper_references')
    op.drop_index(op.f('ix_paper_refs_matched_paper_id'), table_name='paper_references')
    op.drop_index(op.f('ix_paper_refs_paper_id'), table_name='paper_references')
    op.create_index(op.f('ix_paper_references_match_status'), 'paper_references', ['match_status'], unique=False)
    op.create_index(op.f('ix_paper_references_matched_paper_id'), 'paper_references', ['matched_paper_id'], unique=False)
    op.create_index(op.f('ix_paper_references_paper_id'), 'paper_references', ['paper_id'], unique=False)
    op.create_index(op.f('ix_paper_references_parsed_doi'), 'paper_references', ['parsed_doi'], unique=False)
    op.create_index(op.f('ix_paper_tags_paper_id'), 'paper_tags', ['paper_id'], unique=False)
    op.create_index(op.f('ix_paper_tags_tag_id'), 'paper_tags', ['tag_id'], unique=False)
    op.create_index(op.f('ix_papers_citation_key'), 'papers', ['citation_key'], unique=True)
    op.create_index(op.f('ix_papers_date_added'), 'papers', ['date_added'], unique=False)
    op.create_index(op.f('ix_papers_rating'), 'papers', ['rating'], unique=False)
    op.create_index(op.f('ix_papers_read_status'), 'papers', ['read_status'], unique=False)
    op.create_index(op.f('ix_papers_validation_status'), 'papers', ['validation_status'], unique=False)
    op.create_index(op.f('ix_papers_year'), 'papers', ['year'], unique=False)
    op.create_index('ix_papers_year_status', 'papers', ['year', 'read_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_papers_year_status', table_name='papers')
    op.drop_index(op.f('ix_papers_year'), table_name='papers')
    op.drop_index(op.f('ix_papers_validation_status'), table_name='papers')
    op.drop_index(op.f('ix_papers_read_status'), table_name='papers')
    op.drop_index(op.f('ix_papers_rating'), table_name='papers')
    op.drop_index(op.f('ix_papers_date_added'), table_name='papers')
    op.drop_index(op.f('ix_papers_citation_key'), table_name='papers')
    op.drop_index(op.f('ix_paper_tags_tag_id'), table_name='paper_tags')
    op.drop_index(op.f('ix_paper_tags_paper_id'), table_name='paper_tags')
    op.drop_index(op.f('ix_paper_references_parsed_doi'), table_name='paper_references')
    op.drop_index(op.f('ix_paper_references_paper_id'), table_name='paper_references')
    op.drop_index(op.f('ix_paper_references_matched_paper_id'), table_name='paper_references')
    op.drop_index(op.f('ix_paper_references_match_status'), table_name='paper_references')
    op.create_index(op.f('ix_paper_refs_paper_id'), 'paper_references', ['paper_id'], unique=False)
    op.create_index(op.f('ix_paper_refs_matched_paper_id'), 'paper_references', ['matched_paper_id'], unique=False)
    op.create_index(op.f('ix_paper_refs_match_status'), 'paper_references', ['match_status'], unique=False)
    op.create_index(op.f('ix_paper_refs_doi'), 'paper_references', ['parsed_doi'], unique=False)
    op.alter_column('paper_references', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index(op.f('ix_paper_collections_paper_id'), table_name='paper_collections')
    op.drop_index(op.f('ix_paper_collections_collection_id'), table_name='paper_collections')
    op.drop_index(op.f('ix_paper_authors_paper_id'), table_name='paper_authors')
    op.drop_index('ix_paper_authors_both', table_name='paper_authors')
    op.drop_index(op.f('ix_paper_authors_author_id'), table_name='paper_authors')
    op.drop_index('ix_notes_paper_type', table_name='notes')
    op.drop_index(op.f('ix_notes_paper_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_note_type'), table_name='notes')
    op.drop_index(op.f('ix_collections_parent_id'), table_name='collections')
    op.drop_index(op.f('ix_collections_name'), table_name='collections')
    op.drop_index(op.f('ix_authors_name'), table_name='authors')
    op.create_table('papers_fts_idx',
    sa.Column('segid', sa.NullType(), nullable=False),
    sa.Column('term', sa.NullType(), nullable=False),
    sa.Column('pgno', sa.NullType(), nullable=True),
    sa.PrimaryKeyConstraint('segid', 'term')
    )
    op.create_table('papers_fts_data',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('block', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('papers_fts_config',
    sa.Column('k', sa.NullType(), nullable=False),
    sa.Column('v', sa.NullType(), nullable=True),
    sa.PrimaryKeyConstraint('k')
    )
    op.create_table('papers_fts',
    sa.Column('title', sa.NullType(), nullable=True),
    sa.Column('abstract', sa.NullType(), nullable=True)
    )
    op.create_table('papers_fts_docsize',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('sz', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
